services:
  - type: web
    name: shieldbank-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements-api.txt"
    startCommand: "uvicorn api.fastapi:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
